Add a Divider block
zusamarehan/laravel-notion-renderer pull request #5
Opened 2022-10-03 16:25 UTC by praem90

Divider block for the Issue #4

2022-10-04 01:56 UTC, zusamarehan commented
Hi @praem90 

Thanks for taking this up.
Please add screenshots, and update the `README.md` file

2022-10-04 01:58 UTC, zusamarehan requested changes

2022-10-04 01:58 UTC, zusamarehan commented on src/Blocks/Divider.php
> +		$this->result .= '<div class="divide-y"></div>';
Please run Laravel Pint to avoid styling issues.

2022-10-05 18:34 UTC, praem90 commented
Attaching the screenshot using 
![screenshot-notion test-2022 10 06-00_00_56](https://user-images.githubusercontent.com/6235720/194136024-9013dd10-aed7-4a1e-b5f4-d0e568e0a4a7.png)

2022-10-06 17:35 UTC, merged

2022-10-06 17:40 UTC, zusamarehan commented
Thanks for helping out @praem90